[ECHOT-283] Add DatabaseApi methods of Sidechain bitcoin
echoprotocol/pytests pull request #13
Opened 2019-11-25 13:42 UTC by GwinSalbor

[ECHOT-283] Add DatabaseApi methods of Sidechain bitcoin

2019-11-25 15:48 UTC, yauheni-vasilyeu requested changes

2019-11-25 15:48 UTC, eugene-vasilev commented on common/validation.py
> +    btc_address_id_regex = re.compile(r"^1\.19\.(0|[1-9]\d*)$")
Добавь плиз для всех обьектов (https://github.com/echoprotocol/echopy-lib/blob/master/echopy/echobase/config/object_types.py)

2019-11-25 15:48 UTC, eugene-vasilev commented on suites/DatabaseApi/SideChainBitcoin/GetBtcAddress.py
> +from common.validation import Validator
удалить

2019-11-25 15:48 UTC, eugene-vasilev commented on suites/DatabaseApi/SideChainBitcoin/GetBtcAddress.py
> +        self.validator = Validator()
удалить

2019-11-25 15:48 UTC, eugene-vasilev commented on suites/DatabaseApi/SideChainBitcoin/GetBtcDepositScript.py
> +from common.validation import Validator
удалить

2019-11-25 15:48 UTC, eugene-vasilev commented on suites/DatabaseApi/SideChainBitcoin/GetBtcDepositScript.py
> +        self.validator = Validator()
удалить

2019-11-25 15:48 UTC, eugene-vasilev commented on suites/DatabaseApi/SideChainBitcoin/GetBtcAddress.py
> +        self.echo_ops.broadcast(echo=self.echo, list_operations=collected_operation)
is operation completed

2019-11-25 15:48 UTC, eugene-vasilev commented on suites/DatabaseApi/SideChainBitcoin/GetBtcDepositScript.py
> +        btc_address_id = self.get_response(response_id)["result"]
почему btc_address_id?

2019-11-25 15:48 UTC, eugene-vasilev commented on suites/DatabaseApi/SideChainBitcoin/GetBtcDepositScript.py
> +        lcc.log_info("'sidechain_btc_create_address_operation' broadcasted successfully.")
is operation completed

2019-11-25 15:48 UTC, eugene-vasilev commented on test_runner.py
> -
верни здесь строки пустые в файле - слек их убрал

2019-11-26 07:57 UTC, GwinSalbor commented on common/validation.py
> +    btc_address_id_regex = re.compile(r"^1\.19\.(0|[1-9]\d*)$")
старая ссылка, написал все под версию 0.13

2019-11-26 10:03 UTC, yauheni-vasilyeu approved these changes

2019-11-26 10:41 UTC, merged